config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  root 'pages#home'

  use_doorkeeper
  devise_for :users





  draw :api
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: URI::MailTo::EMAIL_REGEXP
  enum role: %i[user admin]

  def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end
end

app/controllers/api/v1/pokemons_controller.rb
class Api::V1::PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.all
    render json: @pokemons
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
    render json: @pokemon
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)
    if @pokemon.save
      render json: @pokemon, status: :created, location: @pokemon
    else
      render json: @pokemon.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    if @pokemon.update(pokemon_params)
      render json: @pokemon
    else
      render json: @pokemon.errors, status: :unprocessable_entity
      end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy
    if @pokemon.destroy
      head :no_content
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :location, :move)
    end
end

app/controllers/api/v1/users/registrations_controller.rb
# frozen_string_literal: true

module Api
    module V1
      module Users
        class RegistrationsController < ApiController
          skip_before_action :doorkeeper_authorize!, only: %i[create]
  
          include DoorkeeperRegisterable
  
          def create
            client_app = Doorkeeper::Application.find_by(uid: params[:client_id])
            unless client_app
              return render json: { error: I18n.t('doorkeeper.errors.messages.invalid_client') },
                            status: :unauthorized
            end
  
            allowed_params = user_params.except(:client_id)
            user = User.new(allowed_params)
  
            if user.save
              render json: render_user(user, client_app), status: :ok
            else
              render json: { errors: user.errors }, status: :unprocessable_entity
            end
          end
  
          private
  
          def user_params
            params.permit(:email, :password, :client_id)
          end
        end
      end
    end
  end

app/controllers/api_controller.rb
class ApiController < ApplicationController
    before_action :doorkeeper_authorize!
    skip_before_action :verify_authenticity_token
    respond_to :json
    def current_user 
        return unless doorkeeper_token
        @current_user ||= User.find_by(id: doorkeeper_token[:resource_owner_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/doorkeeper_registerable.rb
module DoorkeeperRegisterable
    extend ActiveSupport::Concern
  
    def generate_refresh_token
      loop do
        token = SecureRandom.hex(32)
        break token unless Doorkeeper::AccessToken.exists?(refresh_token: token)
      end
    end
  
    def render_user(user, client_app, token_type = 'Bearer')
      access_token = Doorkeeper::AccessToken.create(resource_owner_id: user.id,
                                                    application_id: client_app.id,
                                                    refresh_token: generate_refresh_token,
                                                    expires_in: Doorkeeper.configuration.access_token_expires_in.to_i,
                                                    scopes: '')
  
      {
        id: user.id,
        email: user.email,
        access_token: access_token.token,
        token_type: token_type,
        expires_in: access_token.expires_in,
        refresh_token: access_token.refresh_token,
        created_at: access_token.created_at.to_time.to_i
      }
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @application = Doorkeeper::Application.find_by(name: 'SECRET')

  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]
  # skip_before_action :verify_authenticity_token, only [:webhook, :index, :create]

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy

    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :location, :move)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_admin?
        unless current_user&.admin? 
            redirect_to root_path,
                alert: "You are not authorized_token"
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon Api</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

         <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>

      <%= current_user.email %>
            <%= button_to "logout", destroy_user_session_path, method: :delete  %>
        

 
<h3>
<label for="">Access Id: </label>
<strong  style="color: red;">
<%= @application.uid %>

</strong></h3>

<h3>
<label for="">Access Secret: </label>
<strong style="color: red;">
<%= @application.secret %>
</strong></h3>
<% else %>
  <h1 align="center">You Can Get Acces Key And Secret Key After Sign Up Or Login</h1>
    <h1 align="center"><%= link_to "Sign in", new_user_session_path %></h1> 
    <h1 align="center"><%= link_to "Sign up", new_user_registration_path %></h1>


    
<% end %>
  

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :move, style: "display: block" %>
    <%= form.text_field :move %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/_pokemon.html.erb
<div id="<%= dom_id pokemon %>">
  <p>
    <strong>Name:</strong>
    <%= pokemon.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= pokemon.location %>
  </p>

  <p>
    <strong>Move:</strong>
    <%= pokemon.move %>
  </p>

</div>

app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Show this pokemon", @pokemon %> |
  <%= link_to "Back to pokemons", pokemons_path %>
</div>

app/views/pokemons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pokemons</h1>

<div id="pokemons">
  <% @pokemons.each do |pokemon| %>
    <%= render pokemon %>
    <p>
      <%= link_to "Show this pokemon", pokemon %>
    </p>
  <% end %>
</div>

<%= link_to "New pokemon", new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Back to pokemons", pokemons_path %>
</div>

app/views/pokemons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pokemon %>

<div>
  <%= link_to "Edit this pokemon", edit_pokemon_path(@pokemon) %> |
  <%= link_to "Back to pokemons", pokemons_path %>

  <%= button_to "Destroy this pokemon", @pokemon, method: :delete %>
</div>